# GENERATED FILE. Use with Kubernetes 1.9+
# TO UPDATE, modify files in install/kubernetes/templates and run install/updateVersion.sh
apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    istio: sidecar-injector
spec:
  ports:
  - name: https-webhook # optional
    port: 443
  selector:
    istio: sidecar-injector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sidecar-injector-service-account
  namespace: istio-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    istio: sidecar-injector
spec:
  replicas: 1
  template:
    metadata:
      name: istio-sidecar-injector
      labels:
        istio: sidecar-injector
    spec:
      serviceAccountName: istio-sidecar-injector-service-account
      containers:
        - name: webhook
          image: docker.io/istio/sidecar_injector:0.7.1
          imagePullPolicy: IfNotPresent
          args:
            - --tlsCertFile=/etc/istio/certs/cert.pem
            - --tlsKeyFile=/etc/istio/certs/key.pem
            - --injectConfig=/etc/istio/inject/config
            - --meshConfig=/etc/istio/config/mesh
            - --healthCheckInterval=2s
            - --healthCheckFile=/health
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
            readOnly: true
          - name: certs
            mountPath: /etc/istio/certs
            readOnly: true
          - name: inject-config
            mountPath: /etc/istio/inject
            readOnly: true
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/health
                - --interval=2s
            initialDelaySeconds: 4
            periodSeconds: 4
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/health
                - --interval=2s
            initialDelaySeconds: 4
            periodSeconds: 4
      volumes:
      - name: config-volume
        configMap:
          name: istio
      - name: certs
        secret:
          secretName: sidecar-injector-certs
      - name: inject-config
        configMap:
          name: istio-inject
          items:
          - key: config
            path: config
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: istio-system
        path: "/inject"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZSVENDQXkyZ0F3SUJBZ0lKQUpDY2V2SUhyVWNVTUEwR0NTcUdTSWIzRFFFQkN3VUFNRGt4TnpBMUJnTlYKQkFNTUxqSTFNV015TUdSallXTXhPVFJpWkRGaVlUVmhPVGxsWXpRMU5qazJaVEEwTFd0MVltVnlibVYwWlhNdApZMkV3SGhjTk1UZ3dOREF6TVRZMU1qUXhXaGNOTkRVd09ERTVNVFkxTWpReFdqQTVNVGN3TlFZRFZRUUREQzR5Ck5URmpNakJrWTJGak1UazBZbVF4WW1FMVlUazVaV00wTlRZNU5tVXdOQzFyZFdKbGNtNWxkR1Z6TFdOaE1JSUMKSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXVIelBiQVRURCtZdVl3MzQrYXdhV3IycwpOamhvNWNmdWd3SGgvd2VOSWwxWkM0eUpVZWVCYVBFNmR5QkxhRDVhRi9GUkNENHJDYW9CdXJPL05TdmxSZ3Q2Ci9xSVUrZGhMTG1vL1RVdENlUGpjTStXZXJFZnV2ZGpGdmRDMWtGTGNNQlMvRHRqTElHbGdCTHB3ektmb2hCU0MKTlQ4bHFpYjhvUFZnNG9nT3dWOHY1YXJTUzVhbFJWTmcrTzNaYmgzTlhlWFZvZCswWWQ1WGtjWEIvdVpjZ3hnLwpYTTlyT2p0S3hzQ2VUZ3dhVmRHaHpZUHJCQkh6VjZEb3VqZHNpM0taaTlSS21sSjZTeEFhQ1lzTk5wNHV3QlB0Cm1HNkYraGZXWXdDaU1KSWQzeXQxZlJRSk1IQ3dVQU1sWCtRT29JWHpJNkdQblczN1NNaVBYRUdvZHF3cWt3SkgKZUFESklnbmNoT0pSRzY0dlVQVHRFS2hsYksrWW1tQWJHUjhZU2c3RFlFbFJjcTNqVVljTS9NbjRFN3J6SlppdwpmZ2c1azhXN0tzQUJqaFBUeUJlL0tGRW9lOUx4ejMxVTgyb0lvc2UvbmFSYmZ0NEd4SE5aNjdNV2dMNzhyME16CjhLK0R5UWxNclUrVmJiM2VReG5ySWdOdFB2NEVoNFFKNjlKZWV6eUNzeTBicWhHandzaXUrTXhaSzRCYkw0emsKcC8xNHlKUWY1eDY2SjJ5RkFLZTNMYlFtYTMrSHJtN2FMUHNWeTZBLy9ZUXo1ek5Pd2wvMmsvU3UvVFprZTNDcwo3TkpUT3RlRDVaUzNNSGliN2JxWHYwSFJaN0dhZzFicmYzYVh3RFcyb20xQlpOckRWOFhWQ0xuUkhtNlZxZjBrCmUwQ2F4K1czTDYvczRqazZTUGtDQXdFQUFhTlFNRTR3SFFZRFZSME9CQllFRkNXNExQbWdCd3dXbDFuTjc2TE0KMEhmaHNiejJNQjhHQTFVZEl3UVlNQmFBRkNXNExQbWdCd3dXbDFuTjc2TE0wSGZoc2J6Mk1Bd0dBMVVkRXdRRgpNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFEVzhSeVp5WGdnbkFDejRELysyUGZFTkdSdDIyS2RCCjNnSG1Qc1pDRUFzRUxzeWREZXNIK2dXNks0YmR3QVpRc3N0SGl0LzNnYjcxNUVFc3ZVM3g4Y1JubHlBMHlIYlIKWXZvTkJxSmI3Vjg4WmU0UU9Gd1BST21lbjQxU09PUUdOUnBHYll1dkp3VnVmMXdWSFg0M1FxbmZCQ0VEL3M4eAp5MDNNOVRhOFI2STlUTzNkL1ZSYjBiQmk0VUZKZXNEVjlZMVIzbldQUEp3MWx1TEVhRUZEdDlGeDZBN2t0SjlvCjhRb2wwVUMyQnY5QzJ5LzVBVjVpc3JpS0NRRXpEK0hVaFBCaUhQOWJzSGx3NjB4ek1JaVZTNklkdkxlT2VhdlAKWnBxQjhCQzBxa3diQ0Vkb1hUbjZzZzZwNlQvUTFMalFwcFp4UitUTU9GSE1OMVhVOURPSm1WcjVIRkZoMXA0Wgo1NFEyZHkxQWVtYVYvUU5qdXdoVjBvbXBOWVpvZ0MvMUh4aHNGdmRXNVI4S042MzF0Zm9GRFd0V1ZVWWhObm11ClpWcW5pWENZWS8wdkwxOEY5OHpzVm1od2lWVE9keVdXT0xtenVZcUZHUFArV1Q5b2g5L1ZVd0dVVnJIVlZ1YVIKczhZRzZTKzRTNk51bHJDQlA1Z1BoVXhTYlVZdGFLck5LVDNRdjA2ZElhNStVM0phYS9lRXk2aS9vOEd3cVNocgpYdW45TjhuR0JnZWNWSmtXOUlhVytXZUV2bXAvaXRhUlRpSXRoQnNXcW9DRkFPY2w3VXRhR2k3RVovNVlaUlA2CmtZcHRkdFlkT2RCbDdnbFBteU52N1ZkSnMybEw4b0JlNlhUNGt3Y3VGOGJkdHQvSVBGN3E4d21rbk1pM25iUVEKbkRJNXcvV1o2bXowCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
---
